SCRIPT_FILE=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT_FILE")
LIB_PATH="$SCRIPT_PATH/../lib"
JADE_JAR="$LIB_PATH/jade.jar"
CLASSES_PATH="$SCRIPT_PATH/classes"
SOURCE_PATH="$SCRIPT_PATH/src"
SOURCE_FILES="$SOURCE_PATH/*.java"

ANDROID_LIB_PATH="$SCRIPT_PATH/../../android/app/libs"

REACTIVEJADE_JAR="$LIB_PATH/ReactiveJade.jar"

rm -rf $CLASSES_PATH
mkdir $CLASSES_PATH
javac -cp $JADE_JAR -d $CLASSES_PATH $SOURCE_FILES
jar -cf $REACTIVEJADE_JAR -C $CLASSES_PATH .

rm $ANDROID_LIB_PATH/ReactiveJade.jar
cp $REACTIVEJADE_JAR $ANDROID_LIB_PATH
