SCRIPT_FILE=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT_FILE")
LIB_PATH="$SCRIPT_PATH/../lib"
JADE_JAR="$LIB_PATH/jade.jar"
CLASSES_PATH="$SCRIPT_PATH/classes"
SOURCE_PATH="$SCRIPT_PATH/src"
SOURCE_FILES="$SOURCE_PATH/*.java"
DIST_PATH="$SCRIPT_PATH/../dist"

DESKTOP_JAR="$SCRIPT_PATH/ReactiveJadeDesktop.jar"

# REACTIVEJADE_JAR="$LIB_PATH/ReactiveJade.jar"
# HARDWARESNIFFER_JAR="$LIB_PATH/HardwareSniffer.jar"

rm -rf $CLASSES_PATH
mkdir $CLASSES_PATH

javac -cp $JADE_JAR -d $CLASSES_PATH $SOURCE_FILES
jar -cvfm $DESKTOP_JAR Manifest.txt -C $CLASSES_PATH . $JADE_JAR
